server:
  port: 8081
  servlet:
    context-path: /    session:      timeout: 60
  connection-timeout: 82000
# 应用自定义配置
logging:
    config: classpath:log4j2-dev.xml
spring:
    output:      ansi:       enabled: ALWAYS
    #jackson:      #date-format: yyyy-DD-mm HH:mm:ss       #time-zone: GMT+8